# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentType', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='type',
        ),
        migrations.AddField(
            model_name='contenttype',
            name='types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
