# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentType', '0002_auto_20171107_1652'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HKData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(default='')),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('image', models.ImageField(default='NoImage.jpg', upload_to='HKmodel/%Y/&m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_section', to='section.Section')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_string', to='contentType.ContentType')),
            ],
        ),
    ]
